version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
    volumes:
      - ./api:/app/api
      
